server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: naranjax_user
    password: naranjax_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


jwt:
  secret: naranjax-secret-key-change-in-production-minimum-256-bits-required-very-long-string
  expiration: 900000
  refresh-expiration: 604800000
